In [50]:
import pandas as pd

## dim_linea

In [51]:
dim_linea_df = pd.read_csv("data/raw/dim_linea.csv", index_col=0)
dim_linea_df.head(10)

            linea  id_producto
id_linea
1         Línea 1            1
2         Línea 2            2
3         Línea 3            3
4         Línea 4            4
5         Línea 5            5

## dim_producto

In [52]:
dim_producto_df = pd.read_csv("data/raw/dim_producto.csv", index_col=0)
dim_producto_df.head()

,producto,familia,tiempo_ciclo_ideal_seg,precio_unitario_usd
id_producto,,,,
1,"Pantalla 32""",Electrónica,45,140
2,"Pantalla 55""",Electrónica,70,380
3,Refrigerador 14 pies,Línea blanca,110,520
4,Aire acondicionado mini split,Línea blanca,95,430
5,Lavadora 19 kg,Línea blanca,100,450

## dim_proveedor

In [53]:
dim_proveedor_df = pd.read_csv("data/raw/dim_proveedor.csv", index_col=0)
dim_proveedor_df.head()

                          proveedor        categoria_material    pais
id_proveedor
1              Electrónica Pacífico  Componentes electrónicos  México
2                     Paneles Orión               Paneles LCD   Corea
3             Compresores del Norte               Compresores  EE.UU.
4                   PlastiMold Baja      Plásticos inyectados  México
5                 Empaques Frontera          Empaque y cartón  México

In [54]:
dim_proveedor_df.pais.value_counts()

pais
México    7
China     2
Corea     1
EE.UU.    1
Taiwán    1
Name: count, dtype: int64

## dim turno

In [55]:
dim_turno_df = pd.read_csv("data/raw/dim_turno.csv", index_col=0)
dim_turno_df.head()

               turno      horario
id_turno
1           Matutino  06:00-14:00
2         Vespertino  14:00-22:00
3           Nocturno  22:00-06:00

Agregar columnas Inicio - Fin para establecer cada horario

## fact_defectos

In [56]:
fact_defectos_df = pd.read_csv("data/raw/fact_defectos.csv", index_col=0)
fact_defectos_df.head(10)

            id_produccion              tipo_defecto  cantidad
id_defecto
1                       1                 Soldadura         4
2                       1                  Ensamble         2
3                       1   Componente de proveedor         1
4                       1                 Cosmético         1
5                       2                 Soldadura         3
6                       2                  Ensamble         4
7                       2   Componente de proveedor         1
8                       2                 Cosmético         1
9                       2  Falla funcional / prueba         1
10                      2                   Empaque         3

In [57]:
fact_defectos_df.tipo_defecto.value_counts()

tipo_defecto
Ensamble                    3920
Soldadura                   3785
Cosmético                   3756
Componente de proveedor     3438
Falla funcional / prueba    2898
Empaque                     1777
Name: count, dtype: int64

In [58]:
fact_defectos_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19574 entries, 1 to 19574
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_produccion  19574 non-null  int64
 1   tipo_defecto   19574 non-null  str
 2   cantidad       19574 non-null  int64
dtypes: int64(2), str(1)
memory usage: 458.9 KB

## fact entregas proveedor

In [59]:
fact_entregas_proveedor_df = pd.read_csv("data/raw/fact_entregas_proveedor.csv", index_col=0)
fact_entregas_proveedor_df.head(10)

,fecha_oc,id_proveedor,fecha_prometida,fecha_entrega,cantidad_ordenada,cantidad_recibida,cantidad_rechazada,costo_unitario_usd
id_oc,,,,,,,,
1,2025-08-23,10,2025-10-02,2025-10-02,19319,19319,428,11.89
2,2025-08-25,12,2025-10-04,2025-10-06,2878,2878,79,28.39
3,2025-08-27,12,2025-10-05,2025-10-03,4206,4206,114,26.77
4,2025-08-31,7,2025-10-01,2025-10-01,5071,5071,44,19.05
5,2025-09-01,12,2025-10-08,2025-10-06,3866,3866,92,29.42
6,2025-09-01,12,2025-10-02,2025-10-02,16629,16629,418,29.31
7,2025-09-02,10,2025-10-01,2025-10-04,15392,15154,274,11.48
8,2025-09-02,12,2025-10-10,2025-10-08,11596,11596,308,26.08
9,2025-09-04,10,2025-10-13,2025-10-16,15806,15806,317,11.02
10,2025-09-04,12,2025-10-08,2025-10-06,13143,13143,328,29.54

In [60]:
fact_entregas_proveedor_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3144 entries, 1 to 3144
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   fecha_oc            3144 non-null   str
 1   id_proveedor        3144 non-null   int64
 2   fecha_prometida     3144 non-null   str
 3   fecha_entrega       3144 non-null   str
 4   cantidad_ordenada   3144 non-null   int64
 5   cantidad_recibida   3144 non-null   int64
 6   cantidad_rechazada  3144 non-null   int64
 7   costo_unitario_usd  3144 non-null   float64
dtypes: float64(1), int64(4), str(3)
memory usage: 196.6 KB

In [61]:
fact_entregas_proveedor_df.fecha_oc.str.match(r'^\d{4}-\d{2}-\d{2}$').value_counts()

fecha_oc
True    3144
Name: count, dtype: int64

In [62]:
fact_entregas_proveedor_df.fecha_entrega.str.match(r'^\d{4}-\d{2}-\d{2}$').value_counts()

fecha_entrega
True    3144
Name: count, dtype: int64

In [63]:
fact_entregas_proveedor_df.fecha_prometida.str.match(r'^\d{4}-\d{2}-\d{2}$').value_counts()

fecha_prometida
True    3144
Name: count, dtype: int64

## fact paros

In [64]:
fact_paros_df = pd.read_csv("data/raw/fact_paros.csv", index_col=0)
fact_paros_df.head(10)

,id_produccion,fecha,id_linea,id_turno,categoria_paro,causa,duracion_min
id_paro,,,,,,,
1,1,2025-10-01,1,1,Mantenimiento planeado,Lubricación,6
2,1,2025-10-01,1,1,Mantenimiento planeado,Limpieza profunda,17
3,3,2025-10-01,1,3,Cambio de modelo,Cambio de programa,21
4,4,2025-10-01,2,1,Falta de material,Esperando componente,20
5,6,2025-10-01,2,3,Falta de material,Esperando componente,18
6,6,2025-10-01,2,3,Falla de equipo,Banda transportadora,18
7,6,2025-10-01,2,3,Cambio de modelo,Cambio de herramental,29
8,7,2025-10-01,3,1,Falla de equipo,Banda transportadora,17
9,7,2025-10-01,3,1,Mantenimiento planeado,Limpieza profunda,29
10,7,2025-10-01,3,1,Cambio de modelo,Cambio de herramental,23

In [65]:
fact_paros_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7350 entries, 1 to 7350
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_produccion   7350 non-null   int64
 1   fecha           7350 non-null   str
 2   id_linea        7350 non-null   int64
 3   id_turno        7350 non-null   int64
 4   categoria_paro  7350 non-null   str
 5   causa           7350 non-null   str
 6   duracion_min    7350 non-null   int64
dtypes: int64(4), str(3)
memory usage: 402.1 KB

In [69]:
fact_paros_df.fecha.str.match(r'^\d{4}-\d{2}-\d{2}$').value_counts()

fecha
True    7350
Name: count, dtype: int64

In [66]:
fact_paros_df.categoria_paro.value_counts()

categoria_paro
Falla de equipo           2453
Cambio de modelo          1298
Falta de material         1272
Ajuste / calibración      1015
Mantenimiento planeado     899
Falta de personal          413
Name: count, dtype: int64

In [70]:

fact_paros_df.causa.value_counts()

causa
Falla eléctrica             514
Sensor descalibrado         510
Banda transportadora        484
Falla de motor              479
Fuga neumática              466
Esperando componente        453
Cambio de programa          446
Cambio de herramental       433
Material en inspección      429
Ajuste de línea             419
Faltante en almacén         390
Ajuste de torque            346
Calibración de probador     343
Ajuste de soldadora         326
Lubricación                 317
Limpieza profunda           292
Mantenimiento preventivo    290
Rotación de personal        152
Capacitación                140
Ausentismo                  121
Name: count, dtype: int64

## fact paros

In [71]:
fact_paros_df = pd.read_csv("data/raw/fact_paros.csv", index_col=0)
fact_paros_df.head()

,id_produccion,fecha,id_linea,id_turno,categoria_paro,causa,duracion_min
id_paro,,,,,,,
1,1,2025-10-01,1,1,Mantenimiento planeado,Lubricación,6
2,1,2025-10-01,1,1,Mantenimiento planeado,Limpieza profunda,17
3,3,2025-10-01,1,3,Cambio de modelo,Cambio de programa,21
4,4,2025-10-01,2,1,Falta de material,Esperando componente,20
5,6,2025-10-01,2,3,Falta de material,Esperando componente,18

In [72]:
fact_paros_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7350 entries, 1 to 7350
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_produccion   7350 non-null   int64
 1   fecha           7350 non-null   str
 2   id_linea        7350 non-null   int64
 3   id_turno        7350 non-null   int64
 4   categoria_paro  7350 non-null   str
 5   causa           7350 non-null   str
 6   duracion_min    7350 non-null   int64
dtypes: int64(4), str(3)
memory usage: 402.1 KB

In [73]:
fact_paros_df.fecha.str.match(r'^\d{4}-\d{2}-\d{2}$').value_counts()

fecha
True    7350
Name: count, dtype: int64

In [74]:
fact_paros_df.categoria_paro.value_counts()

categoria_paro
Falla de equipo           2453
Cambio de modelo          1298
Falta de material         1272
Ajuste / calibración      1015
Mantenimiento planeado     899
Falta de personal          413
Name: count, dtype: int64

In [77]:
fact_paros_df.causa.value_counts().sort_index()

causa
Ajuste de línea             419
Ajuste de soldadora         326
Ajuste de torque            346
Ausentismo                  121
Banda transportadora        484
Calibración de probador     343
Cambio de herramental       433
Cambio de programa          446
Capacitación                140
Esperando componente        453
Falla de motor              479
Falla eléctrica             514
Faltante en almacén         390
Fuga neumática              466
Limpieza profunda           292
Lubricación                 317
Mantenimiento preventivo    290
Material en inspección      429
Rotación de personal        152
Sensor descalibrado         510
Name: count, dtype: int64

## fact produccion

In [78]:
fact_produccion_df = pd.read_csv("data/raw/fact_produccion.csv", index_col=0)
fact_produccion_df.head(10)

,fecha,id_linea,id_turno,id_producto,tiempo_planificado_min,tiempo_paro_min,unidades_producidas,unidades_buenas,meta_unidades
id_produccion,,,,,,,,,
1,2025-10-01,1,1,1,450,23,512,504,510
2,2025-10-01,1,2,1,450,0,542,529,510
3,2025-10-01,1,3,1,450,21,506,478,510
4,2025-10-01,2,1,2,450,20,331,322,328
5,2025-10-01,2,2,2,450,0,339,328,328
6,2025-10-01,2,3,2,450,65,266,262,328
7,2025-10-01,3,1,3,450,69,178,174,209
8,2025-10-01,3,2,3,450,0,195,188,209
9,2025-10-01,3,3,3,450,19,194,189,209
10,2025-10-01,4,1,4,450,79,207,199,242

In [79]:
fact_produccion_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4695 entries, 1 to 4695
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   fecha                   4695 non-null   str
 1   id_linea                4695 non-null   int64
 2   id_turno                4695 non-null   int64
 3   id_producto             4695 non-null   int64
 4   tiempo_planificado_min  4695 non-null   int64
 5   tiempo_paro_min         4695 non-null   int64
 6   unidades_producidas     4695 non-null   int64
 7   unidades_buenas         4695 non-null   int64
 8   meta_unidades           4695 non-null   int64
dtypes: int64(8), str(1)
memory usage: 330.2 KB

In [80]:
fact_produccion_df.fecha.str.match(r'^\d{4}-\d{2}-\d{2}$').value_counts()

fecha
True    4695
Name: count, dtype: int64

## fact tickets ti

In [82]:
fact_tickets_df = pd.read_csv("data/raw/fact_tickets_ti.csv", index_col=0)
fact_tickets_df.head(10)

,fecha_creacion,fecha_resolucion,categoria,prioridad,area_solicitante,tecnico,canal,satisfaccion
id_ticket,,,,,,,,
TCK-000001,2025-10-01 06:07:00,2025-10-01 08:01:39,Software,Baja,Ingeniería,Ana,Portal,5.0
TCK-000002,2025-10-01 06:35:00,2025-10-01 10:57:28,Software,Crítica,Producción,Marco,Correo,2.0
TCK-000003,2025-10-01 10:59:00,2025-10-01 16:16:36,Hardware,Crítica,Finanzas,Valeria,Correo,3.0
TCK-000004,2025-10-01 11:12:00,2025-10-01 15:34:34,Sistemas de producción,Alta,Producción,Ana,Portal,NaN
TCK-000005,2025-10-01 13:01:00,2025-10-01 16:36:58,Impresoras,Media,Compras,Diego,Teléfono,4.0
TCK-000006,2025-10-01 13:34:00,2025-10-01 15:59:11,Software,Media,Finanzas,Marco,Teléfono,5.0
TCK-000007,2025-10-01 14:33:00,2025-10-02 07:28:59,Otros,Media,Ingeniería,Diego,Portal,NaN
TCK-000008,2025-10-01 15:21:00,2025-10-01 17:52:52,Sistemas de producción,Alta,Ingeniería,Sofía,Presencial,NaN
TCK-000009,2025-10-01 17:01:00,2025-10-01 19:54:40,Accesos y cuentas,Baja,Ingeniería,Ana,Correo,NaN
TCK-000010,2025-10-01 17:07:00,2025-10-01 19:47:23,Accesos y cuentas,Baja,Ingeniería,Sofía,Presencial,5.0

In [83]:
fact_tickets_df.info()

<class 'pandas.DataFrame'>
Index: 3748 entries, TCK-000001 to TCK-003726
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_creacion    3748 non-null   str
 1   fecha_resolucion  3747 non-null   str
 2   categoria         3748 non-null   str
 3   prioridad         3748 non-null   str
 4   area_solicitante  3702 non-null   str
 5   tecnico           3748 non-null   str
 6   canal             3748 non-null   str
 7   satisfaccion      2072 non-null   float64
dtypes: float64(1), str(7)
memory usage: 263.5+ KB

In [86]:
fact_tickets_df.fecha_creacion.str.match(r'^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$').value_counts()

fecha_creacion
True    3748
Name: count, dtype: int64

In [87]:
fact_tickets_df.fecha_resolucion.str.match(r'^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$').value_counts()

fecha_resolucion
True     3747
False       1
Name: count, dtype: int64

In [94]:
fact_tickets_df[fact_tickets_df.fecha_resolucion.str.match(r'^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$') == False]

,fecha_creacion,fecha_resolucion,categoria,prioridad,area_solicitante,tecnico,canal,satisfaccion
id_ticket,,,,,,,,
TCK-003721,2026-09-30 11:09:00,NaN,Hardware,Media,Producción,Luis,Presencial,NaN

In [89]:
fact_tickets_df.categoria.value_counts().sort_index()

categoria
 Accesos y cuentas            5
 Hardware                     5
 Impresoras                   6
 Otros                        1
 Red y conectividad           6
 Sistemas de producción       5
 Software                     8
ACCESOS Y CUENTAS             9
Accesos y cuentas           791
HARDWARE                      6
Hardware                    571
IMPRESORAS                    1
Impresoras                  352
OTROS                         2
Otros                       172
RED Y CONECTIVIDAD            5
Red y conectividad          465
SISTEMAS DE PRODUCCIÓN        3
SOFTWARE                     12
Sistemas de producción      323
Software                    965
accesos y cuentas            10
hardware                      8
impresoras                    1
otros                         1
red y conectividad            5
sistemas de producción        3
software                      7
Name: count, dtype: int64

In [96]:
fact_tickets_df.categoria.str.strip().str.lower().value_counts().sort_index()

categoria
accesos y cuentas         815
hardware                  590
impresoras                360
otros                     176
red y conectividad        481
sistemas de producción    334
software                  992
Name: count, dtype: int64

In [90]:
fact_tickets_df.prioridad.value_counts().sort_index()

prioridad
Alta        744
Baja       1181
Crítica     307
Media      1516
Name: count, dtype: int64

In [91]:
fact_tickets_df.area_solicitante.value_counts().sort_index()

area_solicitante
Almacén              452
Calidad              457
Compras              256
Finanzas             250
Ingeniería           541
Logística            287
Producción          1265
Recursos Humanos     194
Name: count, dtype: int64

In [92]:
fact_tickets_df.tecnico.value_counts().sort_index()

tecnico
Ana        654
Diego      631
Luis       608
Marco      611
Sofía      633
Valeria    611
Name: count, dtype: int64

In [93]:
fact_tickets_df.canal.value_counts().sort_index()

canal
Correo         727
Portal        1525
Presencial     580
Teléfono       916
Name: count, dtype: int64

In [95]:
fact_tickets_df.isna().sum()

fecha_creacion         0
fecha_resolucion       1
categoria              0
prioridad              0
area_solicitante      46
tecnico                0
canal                  0
satisfaccion        1676
dtype: int64

Agregar columna Estatus para validar si un ticket aun no se a respondido -
Limpiar columna categoria - 
agregar a area solicitante la categoria "sin especificar" para datos nulos -
quedarse con los nulos de satisfaccion -